### ISSUE TITLE
Code does not work anymore

### ISSUE THREAD

**Issue by wesleylex** [2captcha/2captcha-api-examples#12]
the code does not open does more appear white box in low and also can not get site recaptcha site error ai when going to 2captcha
I need to update the code

**Comment by 2captcha** [comment]
Hello,What code are you talking about?25.08.2018, 19:41, "wesleylex" <notifications@github.com>:the code does not open does more appear white box in low and also can not get site recaptcha site error ai when going to 2captcha
I need to update the code

**Comment by wesleylex** [comment]
none of these codes work more accurate than revision
https://github.com/2captcha/2captcha-api-examples/tree/master/ReCaptchaAPIExamples/iMacrosExample

**Comment by shakilrhamankhan123** [comment]
i am not work this side because this is some time show off many problems
for stop working
