### ISSUE TITLE
google's recaptcha demo doesnt work

### ISSUE THREAD

**Issue by mrWiga** [2captcha/2captcha-api-examples#13]
Hi,

Thank you for this great script! I have tested your script but it's not working with google's recaptcha demo anymore. Could you please advise? Thanks
It failed and still ask to confirm.

**Comment by mrWiga** [comment]
Solved by recording the hidden field.

**Comment by mikelam14** [comment]
> Solved by recording the hidden field.

Could you elaborate on the hidden field?
