### ISSUE TITLE
iMacros test code fails with demo page

### ISSUE THREAD

**Issue by anonydev** [2captcha/2captcha-api-examples#4]
The iMacros test code doesn't work with Google's demo page https://www.google.com/recaptcha/api2/demo. It throws the message "Please verify that you are not a robot" after submission. 

I checked the demo page source and saw it uses a callback function onSuccess. I tried changing the code as follows; still the same result  "Please verify that you are not a robot".

```
URL GOTO=https://www.google.com/recaptcha/api2/demo
...
TAG POS=1 TYPE=TEXTAREA FORM=ID:* ATTR=ID:g-recaptcha-response CONTENT={{answer}}
WAIT SECONDS=10
URL GOTO=javascript:onSuccess();
WAIT SECONDS=10
'YOUR SUBMİT BUTTON HERE!!!
TAG POS=1 TYPE=INPUT:SUBMIT FORM=ID:recaptcha-demo-form ATTR=ID:recaptcha-demo-submit
'end
```

For reference, I've attached the full iMacros file.
[recaptcha_v2_sample.iim.txt](https://github.com/2captcha/2captcha-api-examples/files/1152795/recaptcha_v2_sample.iim.txt)

**Comment by 2captcha** [comment]
We've updated the example. Now it should work with google's recaptcha demo.
For any other website you should change the code to make it working.
