### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Judical** [2captcha/2captcha-api-examples#5]
Error wrong captcha ID.

**Comment by 2captcha** [comment]
Hi @Judical
Could you please describe the issue in details?
Please note: there are just examples of code to work with our API, not ready to use solutions.

**Comment by Judical** [comment]
I am running it as is with my 2captcha API key.

It loads the google captcha test page.
Gives an error about the URL then error about the captcha ID.

**Comment by 2captcha** [comment]
Which script you're running?
Could you provide the output of the script?

**Comment by Judical** [comment]
https://github.com/2captcha/2captcha-api-examples/tree/master/ReCaptcha%20v2%20API%20Examples/iMacros%20Example

This is what I am running.

**Comment by 2captcha** [comment]
We've updated the example. Now it should work with google's recaptcha demo.
For any other website you should change the code to make it working.
