### ISSUE TITLE
`pageurl` is required param. but don't use

### ISSUE THREAD

**Issue by NabiKAZ** [2captcha/2captcha-api-examples#6]
https://github.com/2captcha/2captcha-api-examples/blob/6c0df3318c425edcc59b9e028a19f54ee249ce22/ReCaptcha%20v2%20API%20Examples/PHP%20Example/index.php#L18

`pageurl` is required param. but don't use in here and return `ERROR_PAGEURL`

**Comment by 2captcha** [comment]
Added `pageurl` to the example.
Thanks!
