### ISSUE TITLE
doesnt work for captchas without submit button

### ISSUE THREAD

**Issue by rikimasorati** [2captcha/2captcha-api-examples#7]
I have worked with this script for more than a year now, but the latest captcha I try to solve (https://tinyurl.com/ycefdvpp) does not have a submit button. Everything is filled in correctly but in the end the captcha expires because I cant submit. Any solution?

**Comment by 2captcha** [comment]
There's a callback used on the website. We have some hints for such case in our API guide: https://2captcha.com/2captcha-api#solving_recaptchav2_new
P.S. please use the support section of our website for such questions.
