### ISSUE TITLE
Google captcha 2.0 ERROR_CAPTCHA_UNSOLVABLE

### ISSUE THREAD

**Issue by arnoldblandon** [2captcha/2captcha-api-examples#9]
Good afternoon, I have been trying to solve the google captchav2 with your service, but I always answer error "ERROR_CAPTCHA_UNSOLVABLE", I have performed the steps in this manual without getting results, could you confirm why I always answered the same error ?.

**Comment by 2captcha** [comment]
Hi!
Please submit a ticket on your issue from the website and our staff will assist you: https://2captcha.com/support/faq/62
Thanks!

**Comment by Rolland-K** [comment]
HI
I have same error with " captcha 2.0 ERROR_CAPTCHA_UNSOLVABLE"
for some site, It worked well and for this url
https://www.carsales.com.au/cars
it always return Error below.
please check it and let me know how to solve that problem
 thank you.
as I said my code worked well for some other sites.

**Comment by 2captcha** [comment]
@Rolland-K 
You should use the following pageurl value: https://c.datado.me/captcha/?initialCid

**Comment by gitneeraj** [comment]
> @Rolland-K
> You should use the following pageurl value: https://c.datado.me/captcha/?initialCid

This link is broken.

**Comment by tqk2811** [comment]
I think they solve recaptcha by navigated to that `pageUrl` , and worker solve it. And with site need login they can't see recaptcha
